In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
from sklearn import linear_model, preprocessing, model_selection
import utils_titanic

In [3]:
train = pd.read_csv('titanic_data/train_titanic.csv')
test = pd.read_csv('titanic_data/test_titanic.csv')

print "\nCleaning up some data"
utils_titanic.clean_data(train)
utils_titanic.clean_data(test)


Cleaning up some data


In [1]:
print "\nUse logistic regression"

logistic = linear_model.LogisticRegression()
logistic.fit(features, target)
print(logistic.score(features, target))

scores = model_selection.cross_val_score(logistic, features, target, scoring='accuracy', cv=10)
print scores
print scores.mean()

test_features = test[["Pclass", "Age", "Sex", "Fare", "SibSp", "Parch", "Embarked"]].values
utils_titanic.write_prediction(logistic.predict(test_features), "results/logistic_regression.csv")


print("\nUse polynomial features")
poly = preprocessing.PolynomialFeatures(degree=2)
features_ = poly.fit_transform(features)

clf = linear_model.LogisticRegression(C=10)
clf.fit(features_, target)
print(clf.score(features_, target))

scores = model_selection.cross_val_score(clf, features_, target, scoring='accuracy', cv=10)
print scores
print scores.mean()

test_features_ = poly.fit_transform(test_features)
utils_titanic.write_prediction(clf.predict(test_features_), "results/logistic_regression_poly.csv")


Use logistic regression


NameError: name 'linear_model' is not defined

In [44]:
df = train_data.drop(['Ticket','Cabin'], axis=1)
df = df.dropna()
print(df.describe())
print(df.Survived.value_counts())
train_data_ = df.dropna(axis=0, how='any')

AttributeError: 'NoneType' object has no attribute 'drop'

[[ 3. 22.  0.  1.  0.  0.]
 [ 1. 38.  1.  1.  0.  1.]
 [ 3. 26.  1.  0.  0.  0.]
 ...
 [ 3. 28.  1.  1.  2.  0.]
 [ 1. 26.  0.  0.  0.  1.]
 [ 3. 32.  0.  0.  0.  2.]]


In [45]:
df.describe()
#df.Survived.value_counts()

NameError: name 'df' is not defined

In [9]:
train_data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [12]:
predictors = ['Age', 'Fare', 'Pclass','Embarked']
X = train_data_[predictors]
y = train_data_.Survived
my_tree_model = LogisticRegression()
#my_tree_model.fit(X,y)
print(y.head())

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64


In [46]:
#my_tree_model.fit(X, y)


In [ ]:
train_test_split